config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :comments
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'

  get 'up_vote' => 'posts#up_vote'
  get 'down_vote' => 'posts#down_vote'
  post 'create_comment' => 'comments#create_comment'

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def create_comment
    Comment.create(author: "", user_id: params[:user_id], post_id: params[:post_id],
     comment_extry: params[:comment_extry])
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :user_id, :post_id, :comment_extry)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(score: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    puts "*********"
    @post = Post.new
    @post.update(score: 0)
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # puts "*********"
    @post = Post.new(post_params)
    @post.update(score: 0)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


    def up_vote
      post = Post.find(params[:id])
      post.update(score: post.score + 1)
      redirect_to :back
    end

    def down_vote
      post = Post.find(params[:id])
      post.update(score: post.score - 1)
      redirect_to :back
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :post_entry, :score, :user_id, :link_path)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.number_field :post_id %>
  </div>

  <div class="field">
    <%= f.label :comment_extry %>
    <%= f.text_area :comment_extry %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>User</th>
      <th>Post</th>
      <th>Comment extry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= comment.comment_extry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Comment extry:</strong>
  <%= @comment.comment_extry %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<div class="pull-right">
  			<% if user_signed_in? %>
  				<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
  			<% end %>
  	</div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <!-- <div class="field">
    <%#= f.label :author %>
    <%#= f.text_field :author %>
  </div> -->

  <div class="form-group">
    <%= f.label :post_entry %>
    <%= f.text_area :post_entry %>
  </div>

  <!-- <div class="field">
    <%#= f.label :score %>
    <%#= f.number_field :score %>
  </div> -->

  <!-- <div class="field">
    <%#= f.label :user_id %>
    <%#= f.number_field :user_id %>
  </div> -->

  <div class="form-group">
    <%= f.label "Link URL" %>
    <%= f.text_area :link_path %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Post entry</th>
      <th>Score</th> -->
      <!-- <th>User</th> -->
  <!--     <th colspan="3"></th>
    </tr>
  </thead>

  
  <tbody> -->

<%= link_to 'New Post', new_post_path %>

<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">
          <!-- <td><%= post.title %></td> -->
          <p>Post Score: <%= post.score %></p>
          <p><%= link_to post.title, post.link_path %></p>
          <p>Created by: <%= post.user.username %></p>
          <p>Created at: <%= post.created_at.strftime("%m-%d-%Y %r %Z") %> </p>
          <p>Updated at: <%= post.updated_at.strftime("%m-%d-%Y %r %Z") %> </p>
          <!-- <td><%= post.author %></td> -->
        </div>
        <div class="panel-body">
        <%= post.post_entry %>
        </div>
        <div class="panel-footer">
          <%= link_to 'Show', post %>
          <% if current_user.id == post.user.id %>
            <%= link_to 'Edit', edit_post_path(post) %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
  <!-- </tbody>
</table> -->

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">

        <p>
          <strong>Title:</strong>
          <%#= @post.title %>
          <%= link_to @post.title.to_s, @post.link_path %>
        </p>

        <p>
          <strong>Author:</strong>
          <%= @post.user.username %>
        </p>

        <p>
          <strong>Posted at:</strong>
          <%= @post.created_at.strftime("%m-%d-%Y %r %Z") %>
        </p>

        <p>
          <strong>Updated at:</strong>
          <%= @post.updated_at.strftime("%m-%d-%Y %r %Z") %>
        </p>

        <p>
          <strong>Post entry:</strong>
          <%= @post.post_entry %>
        </p>

        <p>
          <strong>Score:</strong>
          <%= @post.score %>
        </p>
      </div>
    </div>
  </div>
</div>

<!-- <p>
  <strong>User:</strong>
  <%#= @post.user.username %>
</p> -->

<%= link_to '+', up_vote_path(id: @post.id) %>
<%= link_to '-', down_vote_path(id: @post.id) %>

<% if @post.user.id == current_user.id %>
  <%= link_to 'Edit', edit_post_path(@post) %> | 
<% end %>
<%= link_to 'Back', posts_path %>

<%= form_tag(create_comment_path) do %>
  <%= hidden_field_tag :post_id, @post.id %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= text_area_tag :comment_extry, nil, placeholder: "Leave a comment."%>
  <%= submit_tag "Submit" %>
<% end %>


<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-footer">
        <% @post.comments.each do |comment| %>
          <p>
            <%= comment.user.username %> said...<br /><%= comment.comment_extry%>
          </p>
          <p>
            Created at: <%= comment.created_at.strftime("%m-%d-%Y %r %Z") %>
          </p>
          <p>
            Updated at: <%= comment.updated_at.strftime("%m-%d-%Y %r %Z") %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>